name: Invidious
description: An open source alternative front-end to YouTube
slug: invidious
version: 0.1.0
url: https://github.com/yo1frenchtoast/invidous-ha
init: false
webui: http://[HOST]:[PORT:3000]
arch:
  - amd64
ports:
  3000/tcp: 3000
